language: r
cache: packages
latex: false
pandoc: false
fortran: false

env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

matrix:
  include:
    - dist: precise
    - dist: trusty
    - dist: xenial
    - os: osx
    - os: osx
      osx_image: xcode7.3

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change
