language: r
cache: packages
env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.2
      latex: false
    - os: osx
      osx_image: xcode7.3
      latex: false
    - os: osx
      osx_image: beta-xcode6.4
      latex: false

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov(type = "examples")'; fi
